[build]
  command = "npm run build"
  publish = "build/"

[build.environment]
  # This tells Netlify's secret scanner that it's okay for these specific
  # variables to be present in the final build files.
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_STRIPE_PUBLISHABLE_KEY,REACT_APP_API_URL,BROWSER"